blizzard-net/warcraft

src/ArgentPonyWarcraftClient/Utilities/GlobalHttpClient.cs
src/ArgentPonyWarcraftClient/WarcraftClient.cs

HttpClient is intended to be instantiated once and re-used throughout the life of an application.
Especially in server applications, creating a new HttpClient instance for every request will exhaust the
number of sockets available under heavy loads. This will result in SocketException errors.
To reslove this issue I created a singleton class and everytime you create a new WarcraftClient it will grab the current HttpClient instasnce.

Use a single instance of HttpClient

---

src/ArgentPonyWarcraftClient/Utilities/WarcraftClientException.cs
src/ArgentPonyWarcraftClient/WarcraftClient.cs

Fixes #38.  Updated WarcraftClient to capture error response content when a
non-success status code is returned from the World of Warcraft Community
APIs.  The details of the request and response are included in the
message of a WarcraftClientException that is thrown.  API keys in the
request URI are masked for security purposes.  An example error message
looks like the following:
Response code 404 (Not Found) does not indicate success. Request:
https://us.api.battle.net/wow/spell/8056?locale=en_US&apikey={apiKey}
Response: {"status":"nok", "reason": "unable to get spell information."}

Updated WarcraftClient to capture error response

---

README.md
src/ArgentPonyWarcraftClient.Tests/WarcraftClientTests.cs
src/ArgentPonyWarcraftClient/Utilities/AccessToken.cs
src/ArgentPonyWarcraftClient/WarcraftClient.cs

Migration to the library to the updated Blizzard API endpoints based on the OAuth client credentials flow based on instructions in the [Migration Guide](https://develop.battle.net/documentation/guides/migration-guide).  Updated the **README.md** file as well.  Additional work is still needed, but I think this is a good first pass.

Migration to updated API endpoints with OAuth client credentials flow

---

src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj

Replaced PackageLicenseUrl with PackageLicenseExpression based on https://github.com/NuGet/Home/issues/4628.

Replaced PackageLicenseUrl with PackageLicenseExpression

---

src/ArgentPonyWarcraftClient/WarcraftClient.cs

Updated the base URI for the China region from https://cn.api.blizzard.com to https://gateway.battlenet.com.cn.  This matches the current documentation at https://develop.battle.net/documentation/guides/regionality-and-apis.  Also changed the base URI for OAuth for China per the documentation at https://develop.battle.net/documentation/guides/using-oauth.  Resolves #71.

Updated the base URI for the China region

---

src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj

Updated the GitHub URLs in the csproj file that are used for building the NuGet package.  This was necessary after moving the repository from https://github.com/danjagnow/ArgentPonyWarcraftClient to https://github.com/blizzard-net/warcraft.

Updated GitHub repository name

---

.circleci/config.yml
.config/dotnet-tools.json

Improved CircleCI builds.  Builds now occur on Linux (the mcr.microsoft.com/dotnet/core/sdk:3.1 Docker image) instead of Windows.  A workflow was created that separates build and deploy jobs, and the NuGet packages are preserved between jobs.  No meaningful publish step occurs yet.  trx2junit is now installed and used to transform the test results into a format that CircleCI can interpret.

Improved CircleCI builds

---

.circleci/config.yml
build/semver
build/semver_LICENSE.txt
build/set-version.sh
src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj

Added logic for handling package version numbers.  The set-version.sh script uses either the CIRCLE_TAG environment variable or retrieves the most recent tag via git describe --tags.  It sets the version number and suffix to be used by dotnet pack.  Also updated the package icon handling and a few other issues in the csproj file.  Finally, updated to push the NuGet package when tagged.  This last bit is untested.  Hopefully this works as planned.

Added logic for handling package version numbers and publishing

---

.circleci/config.yml
build/set-version.sh

Updated the handling of versions.  A single version is now generated by set-version.sh and passed to the dotnet pack operation in the CircleCI config.yml file.

Updated the handling of versions

---

src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientMythicKeystoneLeaderboardApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientMythicKeystoneLeaderboardApi.cs
src/ArgentPonyWarcraftClient/Models/EnumTypeWithoutName.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneAffix/MythicKeystoneAffixReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/LeaderboardKeystoneAffix.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/LeadingGroup.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/Member.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/MythicKeystoneLeaderboard.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/MythicKeystoneLeaderboardReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/MythicKeystoneLeaderboardsIndex.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/Profile.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecializationReferenceWithoutName.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Realm/RealmReferenceWithoutName.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/MythicKeystoneLeaderboardApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Added support for the Mythic Keystone Leaderboard API.  Added an IWarcraftClientMythicKeystoneLeaderboardApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.  Added some ugly "WithoutName" class variants like EnumTypeWithoutName.

Added support for the Mythic Keystone Leaderboard API

---

src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientMythicRaidLeaderboardApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientMythicRaidLeaderboardApi.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicRaidLeaderboard/MythicRaidLeaderboard.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicRaidLeaderboard/MythicRaidLeaderboardEntry.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicRaidLeaderboard/ZoneReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Realm/RealmReferenceWithoutKey.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/Guild/GuildReferenceWithoutKeyAndFaction.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/MythicRaidLeaderboardApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Added support for the Mythic Raid Leaderboard API.  Added an IWarcraftClientMythicRaidLeaderboardApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.

Added support for the Mythic Raid Leaderboard API

---

src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientPvpTierApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientPvpTierApi.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpLeaderboardEntry.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpTier/PvpTier.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpTier/PvpTierMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpTier/PvpTierReferenceWithoutName.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpTier/PvpTiersIndex.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PvpTierApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Added support for the PvP Tier API.  Added an IWarcraftClientPvpTierApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.

Added support for the PvP Tier API

---

src/ArgentPonyWarcraftClient/Client/ProfileApi/AccountProfileApi.cs
src/ArgentPonyWarcraftClient/Client/WarcraftClient.cs
src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IAccountProfileApi.cs
src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/AccountCharacter.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/AccountCollectionsIndex.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/AccountMount.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/AccountMountsCollectionSummary.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/AccountPet.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/AccountPetsCollectionSummary.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/AccountProfileSummary.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/LinksForAccountProfile.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/Position.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/ProtectedCharacterProfileSummary.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/ProtectedStats.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/AccountProfile/WowAccount.cs
tests/ArgentPonyWarcraftClient.Tests/ProfileApi/AccountProfileApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Added support for the Account Profile API.  Added an IAccountProfileApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.  Refactored the internals of WarcraftClient to allow the access token to be passed as a parameter.

Added support for the Account Profile API

---

src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ArgentPonyWarcraftClient.Extensions.DependencyInjection.csproj
src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj

Updated PackageTags elements to use semicolons instead of spaces as separators between tags, as documented at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#packagetags and noted in https://github.com/blizzard-net/warcraft/pull/143#discussion_r457662591.

Updated PackageTags elements to use semicolons

---

src/ArgentPonyWarcraftClient/Models/Asset.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/Achievement.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementCategoriesIndex.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementCategory.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementCategoryReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementCriteria.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementsIndex.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AggregatesByFaction.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/FactionAchievementAggregates.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/AzeriteEssence/AzeriteEssenceMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Creature/CreatureDisplayMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Creature/CreatureFamilyMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/GuildCrest/GuildCrestBorderMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/GuildCrest/GuildCrestEmblemMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/ItemClassesIndex.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/ItemMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/ItemSetsIndex.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Journal/JournalMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneAffix/MythicKeystoneAffixMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Pet/PetAbilityMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PlayableClassMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecializationMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Profession/ProfessionMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Profession/RecipeMedia.cs
src/ArgentPonyWarcraftClient/Models/Links.cs
src/ArgentPonyWarcraftClient/Models/Media.cs
src/ArgentPonyWarcraftClient/Models/Self.cs

Changed private setters to public in model classes for consistency and because System.Text.Json does not currently support them.  See https://github.com/dotnet/runtime/pull/34675 for details, because this will be supported in .NET 5.

Changed private setters to public in model classes

---

tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/AuctionHouseApiTests.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/TalentApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/AuctionHouseApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/TalentApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Updated the unit and integration tests for the auction house and PvP talents.  The talent and connected realm IDs that were in use for the test are no longer valid, so the tests needed to be updated.

Unit and integration test compatibility fixes

---

src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterSoulbindsApi.cs
src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterSoulbindsApi.cs
src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Covenant/ConduitReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Covenant/CovenantReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Covenant/SoulbindReference.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/TechTalent/TechTalentReference.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSoulbinds/CharacterSoulbinds.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSoulbinds/ConduitRank.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSoulbinds/ConduitSocketTrait.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSoulbinds/SoulbindSelection.cs
src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSoulbinds/SoulbindTrait.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/ProfileApi/CharacterSoulbindsApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterSoulbindsApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Added support for the Character Soulbinds API.  Added an ICharacterSoulbindsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.  Resolves #162.

Added support for the Character Soulbinds API

---

src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMedia/CharacterMediaSummary.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Updated ChararacterMediaSummary to include an Assets property instead of separate AvatarUrl, BustUrl, and RenderUrl properties.  Resolves #167.

Updated ChararacterMediaSummary to include an Assets property

---

.circleci/config.yml
.config/dotnet-tools.json
global.json
tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/TestUtilities/ResilientMessageBus.cs
tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj

Updated all test projects to multitarget netcoreapp2.1 (LTS), netcoreapp3.1 (LTS), and net5.0 (current).  Updated CircleCI to use mcr.microsoft.com/dotnet/sdk:5.0 as the Docker image for building.  Also fixed ResilientMessageBus so it never resets the CanRetry property after it has encountered a potentially recoverable error.  Resolves #169.

Updated tests to multi-target different frameworks

---

src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/Enchantment.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/MythicKeystoneDungeonApiTests.cs

Updated Enchantment properties to match naming conventions, changing enchantment_id to EnchantmentId and Item to SourceItem.
Also updated the ID used in the GetMythicKeystoneDungeonAsync_Gets_MythicKeystoneDungeon test.  The previous ID was no longer valid after the release of new mythic dungeons for the Shadowlands expansion.

Updated Enchantment properties

---

.config/dotnet-tools.json
src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ArgentPonyWarcraftClient.Extensions.DependencyInjection.csproj
src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj

Updated several NuGet packages:
- Updated **Microsoft.NET.Test.Sdk** from 16.7.1 to 16.9.1
- Updated **coverlet.collector** from 1.3.0 to 3.0.3
- Removed an unnecessary dependency on the **Microsoft.Extensions.DependencyInjection** NuGet package.  The **Microsoft.Extensions.Http** dependency pulls in **Microsoft.Extensions.DependencyInjection.Abstractions**, which is sufficient
- Updated **Microsoft.Extensions.Http** from 3.0.0 to 5.0.0
- Updated **System.Text.Json** from 4.7.2 to 5.0.1
- Updated the **dotnet-format** tool from 4.1.131201 to 5.0.211103

Updated NuGet packages

---

.github/workflows/documentation.yml

Added a **documentation.yml** to define a new workflow for GitHub Actions that publishes [Docusaurus](https://docusaurus.io/) docs from the **documentation** branch to the **gh-pages** branch.  This is based on documentation at https://docusaurus.io/docs/deployment#deploying-to-github-pages.

Added documentation.yml for GitHub Actions

---

.github/workflows/build.yml

Fixed the `dotnet nuget push` step.  It requires two asterisks in the wildcard for the *.nupkg name instead of one.  Also removed an unnecessary `github.workspace` prefix.

Fixed the dotnet nuget push step

---

.github/workflows/build.yml
Directory.Build.props

Updated GitHub Actions to build on **ubuntu-latest** instead of **windows-latest** after updating [Microsoft.Build.Artifacts](https://github.com/microsoft/MSBuildSdks/tree/main/src/Artifacts) from 2.1.6 to 2.2.0 to address https://github.com/microsoft/MSBuildSdks/issues/233.  Resolves #189.

Updated GitHub Actions to build on ubuntu-latest

---

src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingReagentSlotTypeReferenceWithoutName.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Profession/CraftedQuantity.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Profession/ModifiedCraftingSlot.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Profession/Recipe.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/ProfessionApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/ProfessionApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Fixed recipe models.  Added `AllianceCraftedItem` and `HordeCraftedItem` properties for recipes that produce faction-specific items.  Added a `ModifiedCraftingSlots` property for recipes that allow modified crafting.  Added a supporting `ModifiedCraftingSlot` model type.  Updated the `CraftedQuantity` model type to add a `Value` property and made the existing `Minimum` and `Maximum` properties nullable since they are not always present.  Added new tests to ensure these cases are tested.
Resolves #197.

Fixed recipe models

---

.github/workflows/build.yml

GitHub Actions build improvements.  Updated all references to actions to use the git commit SHA to securely reference a fixed version.  Also updated the .NET 5 SDK version from 5.0.201 to 5.0.302 (current latest).

GitHub Actions build improvements

---

.config/dotnet-tools.json
.github/workflows/build.yml
Directory.Build.props
tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
tests/ArgentPonyWarcraftClient.Tests.Assertions/ArgentPonyWarcraftClient.Tests.Assertions.csproj
tests/ArgentPonyWarcraftClient.Tests.Assertions/RequestResultAssertions.cs
tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj

* Updated the [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/) NuGet package from 16.10.0 to 17.0.0.
* Updated the [FluentAssertions](https://www.nuget.org/packages/FluentAssertions/) NuGet package from 5.10.3 to 6.2.0.  This required a small change to the `RequestResultAssertions` class due to constructor changes in the base `ReferenceTypeAssertions` class.
* Updated the [FluentAssertions.Json](https://www.nuget.org/packages/FluentAssertions.Json/) NuGet package from 5.5.0 to 6.0.0.
* Updated the [coverlet.collector](https://www.nuget.org/packages/coverlet.collector/) NuGet package from 3.0.3 to 3.1.0.
* Updated the [Nerdbank.GitVersioning](https://www.nuget.org/packages/Nerdbank.GitVersioning/) NuGet package and associated …

Updated NuGet packages and GitHub Actions build steps

---

.config/dotnet-tools.json
.github/workflows/build.yml
Directory.Build.props
global.json
src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ArgentPonyWarcraftClient.Extensions.DependencyInjection.csproj
src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
src/ArgentPonyWarcraftClient/Models/GameDataApi/AuctionHouse/AuctionsIndex.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/PreviewItem.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneDungeon.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecialization.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Talent/RankDescription.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Talent/Talent.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Talent/TalentTreeReference.cs
tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/MythicKeystoneDungeonApiTests.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/TalentApiTests.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/ProfileApi/CharacterPvpApiTests.cs
tests/ArgentPonyWarcraftClient.Tests.Assertions/ArgentPonyWarcraftClient.Tests.Assertions.csproj
tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/MythicKeystoneDungeonApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/TalentApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
version.json

Dusted off the tests for the Dragonflight expansion.  This is a first step for full support, just updating dependencies and getting all the integration tests working again after API changes and changes in the data.
- Updated the version in the **version.json** file to `8.0-alpha` for the 8.0 release for the Dragonflight expansion.
- Updated all unit test projects to .NET 7.  Updated the GitHub Actions build and **global.json** accordingly.
- Updated all NuGet packages to the latest available.
- Updated `AuctionsIndex`, `MythicKeystoneDungeon`, `PlayableSpecialization`, `PreviewItem`, and `Talent` along with related classes and tests based on the API and data changes for the Dragonflight expansion.
- Updated third party GitHub Actions to the latest versions.

Fixes for Dragonflight 

---

Directory.Build.props
Directory.Packages.props
src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ArgentPonyWarcraftClient.Extensions.DependencyInjection.csproj
src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
tests/ArgentPonyWarcraftClient.Tests.Assertions/ArgentPonyWarcraftClient.Tests.Assertions.csproj
tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj

Enabled central package management for NuGet packages.  See https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management for details.  Added **coverlet.collector** to tests where it was missing before.

Enabled central package management for NuGet

---

src/ArgentPonyWarcraftClient/Client/GameDataApi/AuctionHouseApi.cs
src/ArgentPonyWarcraftClient/Client/GameDataApi/PetApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IAuctionHouseApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IPetApi.cs
src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/ITalentApi.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/AuctionHouse/CommoditiesIndex.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/AuctionHouse/Commodity.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/AuctionHouse/CommodityItem.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Pet/PetMedia.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentNodeRank.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/AuctionHouseApiTests.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/PetApiTests.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/TalentApiTests.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/TestUtilities/ClientFactory.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/TestUtilities/RawBlizzardClient.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/AuctionHouseApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PetApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/GameDataApi/TalentApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

- Added support for Commodities on the Auction House API.  The document returned by this call is very large, so it requires special timeout handling.
- Added support for Pet Media on the Pet API.
- Added tests for the Talent Tree Index, Talent Tree, and Talent Tree Nodes on the Talent API.
- Minor tweaks to the /// documentation on the `ITalentApi` interface and the `TalentNodeRank` class.

Dragonflight API support

---

src/ArgentPonyWarcraftClient/Client/WarcraftClient.cs

fix: updated oauth hosts according latest battlenet api changes

---

src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PlayableClass.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableRace/PlayableRace.cs
tests/ArgentPonyWarcraftClient.Tests/ClientFactory.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Added some fixes to get the unit and integration tests working again.  Updated the `ClientFactory` for the unit tests to expect https://oauth.battle.net/oauth/token instead of https://us.battle.net/oauth/token to adapt to the changes in https://github.com/blizzard-net/warcraft/pull/212.  Also updated the `PlayableClass` and `PlayableRace` model classes to add new properties that indicate which classes and races can be combined.

Fixes to get tests working again

---

src/ArgentPonyWarcraftClient/Models/GameDataApi/Journal/Instance.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/LeadingGroup.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PlayableClass.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecialization.cs
src/ArgentPonyWarcraftClient/Models/GameDataApi/Region/Region.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/TalentApiTests.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx

Added Keystone rating (score + color) for leaderboard entries.
Pvp talent moved to 40 as 11 no longer exists.
Resolved missing 10.2.5 properties.

Adding new fields for Keystone Leaderboard. Fixing tests while i was at it.

---

.config/dotnet-tools.json
.github/workflows/build.yml
Directory.Build.props
Directory.Packages.props
LICENSE
README.md
global.json
src/ArgentPonyWarcraftClient/Client/WarcraftClient.cs
tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
tests/ArgentPonyWarcraftClient.Integration.Tests/ProfileApi/CharacterMediaApiTests.cs
tests/ArgentPonyWarcraftClient.Integration.Tests/TestUtilities/RawBlizzardClient.cs
tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj
tests/ArgentPonyWarcraftClient.Tests/ClientFactory.cs

- Updated the build to use the .NET 8 SDK: 7.0.103 to 8.0.200.
- Updated NuGet packages to the latest available versions.
- Updated the version of **nbgv** in **dotnet-tools.json** to match the current NuGet package.
- Updated GitHub Actions references to the latest available.
- Updated the copyright year in **Directory.Build.props** and **LICENSE**.
- Updated the **README.md** to mention .NET 8 instead of .NET 6 and .NET 7.
- Updated unit test projects from .NET 7 to .NET 8.
- Updated OAuth-related operations to call `EnsureSuccessStatusCode` on the `HttpResponseMessage` before attempting to deserialize the `OAuthAccessToken` from the response.  Also renamed a variable to avoid confusion.
- Updated the `BuildMockClient` methods in the `ClientFactory` to match the current expected base …

Updated to .NET 8 and fixed tests

---

.github/workflows/build.yml
Directory.Build.props
Directory.Packages.props
src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ArgentPonyWarcraftClient.Extensions.DependencyInjection.csproj
src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj

Fixed issues with NuGet packages.  Updated the **Directory.Build.props** and **Directory.Packages.props** to rely on the .NET 8 artifacts output layout (see https://learn.microsoft.com/en-us/dotnet/core/sdk/artifacts-output) instead of the **Microsoft.Build.Artifacts** SDK.  Updated the GitHub Actions **build.yml** to locate the NuGet packages in their new output path.  Added a `PackageReadmeFile` MSBuild property to the project files to reference the **README.md** that was already included.

Fixed issues with NuGet packages
