blizzard-net/warcraft

- src/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj
- src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
Updated NuGet package dependencies for Newtonsoft.Json, System.ComponentModel.Annotations, Microsoft.NET.Test.Sdk, xunit, and xunit.runner.visualstudio.
> Updated NuGet package dependencies

- src/ArgentPonyWarcraftClient/Models/Race.cs
> Included new race enum values

- src/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- src/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
- src/ArgentPonyWarcraftClient.Tests/WarcraftClientTests.cs
- src/ArgentPonyWarcraftClient/IWarcraftClient.cs
- src/ArgentPonyWarcraftClient/Models/UserAccount.cs
- src/ArgentPonyWarcraftClient/WarcraftClient.cs
Added `GetUserAsync()` and `GetCharactersAsync()` methods to retrieve a user's account information and characters based on a user's OAuth token.  This relates to #52 and #40.  Note that the [AspNet.Security.OAuth.BattleNet](https://www.nuget.org/packages/AspNet.Security.OAuth.BattleNet/) NuGet package supports OAuth integration with Blizzard.  After the user logs in, an ASP.NET Core website can retrieve the token as follows:
``` cs
string accessToken = await HttpContext.GetTokenAsync("access_token");
```
> Added GetUserAsync and GetCharactersAsync methods

- src/ArgentPonyWarcraftClient/Models/Boss.cs
- src/ArgentPonyWarcraftClient/Models/PvpBracket.cs
- src/ArgentPonyWarcraftClient/Models/PvpCharacter.cs
- src/ArgentPonyWarcraftClient/Models/TooltipParams.cs
Added missing properties to support Battle for Azeroth API changes.
> Added missing properties to support BFA changes

- appveyor.yml
- src/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj
- src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
Updated all NuGet packages to the latest stable version and changed the target framework for the unit test project from netcoreapp2.0 to netcoreapp3.1.
> Updated NuGet packages and target framework for unit tests

- README.md
- src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/Item.cs
Updated to target netstandard2.0 instead of netstandard1.1.  Also updated README.md and performed a few other minor tweaks.
> Updated to target netstandard2.0 instead of netstandard1.1

- README.md
- src/ArgentPonyWarcraftClient/Client/ProfileApi/WarcraftClientCharacterProfileApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/IWarcraftClient.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientCharacterProfileApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PlayableClassReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableRace/PlayableRaceReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecializationReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Realm/RealmReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Title/TitleReference.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfile/CharacterProfileSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfile/CharacterStatus.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/Guild/GuildReference.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
- tests/ArgentPonyWarcraftClient.Tests/WarcraftClientTestsCharacterProfileApi.cs
Added support for the Profile API with Character Profile Summary and Character Profile Status.  Added an IWarcraftClientCharacterProfileApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientProfileApi interface.  Also updated the sample code in README.md to use methods for the new Profile API.
> Added Character Profile Summary for Character Profile API

- src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
- src/ArgentPonyWarcraftClient/Client/ProfileApi/WarcraftClientCharacterCollectionsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientCharacterCollectionsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Mount/MountReference.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterCollections/CharacterCollectionsIndex.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterCollections/CharacterMount.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterCollections/CharacterMountsCollectionSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterCollections/CharacterPet.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterCollections/CharacterPetsCollectionSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterCollections/PetStats.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfile/CharacterProfileSummary.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
- tests/ArgentPonyWarcraftClient.Tests/WarcraftClientTestsCharacterCollectionsApi.cs
Added support for the Character Collections API, including mount and pet collections.  Added an IWarcraftClientCharacterCollectionsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientProfileApi interface.
> Added support for the Character Collections API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientMountApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientMountApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Mount/Mount.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Mount/MountsIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
- tests/ArgentPonyWarcraftClient.Tests/WarcraftClientTestsMountApi.cs
Added support for the Mount API.  Added an IWarcraftClientMountApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Mount API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientPlayableClassApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientPlayableClassApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/GenderName.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PlayableClass.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PlayableClassMedia.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PlayableClassesIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/PvpTalentSlots.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/TalentSlot.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PowerType/PowerTypeReference.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
- tests/ArgentPonyWarcraftClient.Tests/WarcraftClientTestsPlayableClassApi.cs
Added support for the Playable Class API.  Added an IWarcraftClientPlayableClassApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Playable Class API

- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/AchievementApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/AuctionHouseApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/ItemApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/JournalApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/MountApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PetApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PlayableClassApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterCollectionsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterProfileApiTests.cs
Reorganized unit test classes, placing many under GameDataApi and ProfileApi folders for organizational purposes.  Shortened class names for simplicity.
> Reorganized unit test classes

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientPlayableRaceApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientPlayableRaceApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/GenderName.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableRace/PlayableRace.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableRace/PlayableRacesIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PlayableRaceApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Playable Race API.  Added an IWarcraftClientPlayableRaceApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Playable Race API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/WarcraftClientCharacterMythicKeystoneProfileApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientCharacterMythicKeystoneProfileApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneDungeonReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystonePeriodReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneSeasonReference.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CharacterMythicKeystoneProfileIndex.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CharacterMythicKeystoneSeasonDetails.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CharacterMythicKeystoneSeasonDetailsReference.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CurrentPeriod.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MemberCharacter.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MythicKeystonePartyMember.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MythicKeystoneProfileCharacter.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MythicKeystoneRun.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterMythicKeystoneProfileApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Mythic Keystone Profile API.  Added an IWarcraftClientCharacterMythicKeystoneProfileApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientProfileApi interface.
> Added support for the Character Mythic Keystone Profile API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientMythicKeystoneAffixApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientMythicKeystoneAffixApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneAffix/MythicKeystoneAffix.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneAffix/MythicKeystoneAffixMedia.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneAffix/MythicKeystoneAffixesIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/MythicKeystoneAffixApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Mythic Keystone Affix API.  Added an IWarcraftClientMythicKeystoneAffixApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Mythic Keystone Affix API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientMythicKeystoneDungeonApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientMythicKeystoneDungeonApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneDungeon.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneDungeonsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystonePeriod.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystonePeriodsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneSeason.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneSeasonsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneUpgrade.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/ZoneReferenceSlug.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/MythicKeystoneDungeonApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Mythic Keystone Dungeon API.  Added an IWarcraftClientMythicKeystoneDungeonApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Mythic Keystone Dungeon API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientQuestApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientQuestApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/Money.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/Quest.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestArea.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestAreaReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestAreasIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestCategoriesIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestCategory.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestCategoryReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestRequirements.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestReward.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestType.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestTypeReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestTypesIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/QuestsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/ReputationReward.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Quest/Units.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationFactionReference.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/QuestApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Quest API.  Added an IWarcraftClientQuestApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Quest API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientSpellApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientSpellApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Spell/Spell.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Spell/SpellMedia.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/SpellApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Spell API.  Added an IWarcraftClientSpellApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Spell API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WarcraftClientPvpSeasonApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWarcraftClientPvpSeasonApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneSeasonsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/Bracket.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpLeaderboard.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpLeaderboardEntry.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpLeaderboardReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpLeaderboardsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpRewardsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpSeason.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpSeasonReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpSeasonReward.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpSeasonsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/SeasonMatchStatistics.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpTier/PvpTierReference.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PvpSeasonApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the PvP Season API.  Added an IWarcraftClientPvpSeasonApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the PvP Season API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/WarcraftClientCharacterAchievements.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientCharacterAchievements.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IWarcraftClientProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/Category.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/CategoryProgress.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/CharacterAchievement.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/CharacterAchievementStatistics.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/CharacterAchievementsSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/Criteria.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/RecentEvent.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/Statistic.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CharacterMythicKeystoneProfileIndex.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CharacterMythicKeystoneSeasonDetails.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfile/CharacterReference.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterAchievementsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Achievements API.  Added an IWarcraftClientCharacterAchievementsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientProfileApi interface.
> Added support for the Character Achievements API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/GuildCrestApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGuildCrestApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/GuildCrest/GuildCrestBorder.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/GuildCrest/GuildCrestBorderMedia.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/GuildCrest/GuildCrestComponentsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/GuildCrest/GuildCrestEmblem.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/GuildCrest/GuildCrestEmblemMedia.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAppearance/GuildCrest.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAppearance/GuildCrestBorderWithColor.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAppearance/GuildCrestEmblemWithColor.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/GuildCrestApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Guild Crest API.  Added an IWarcraftClientGuildCrestApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Guild Crest API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/PlayableSpecializationApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IPlayableSpecializationApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/GenderDescription.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecialization.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecializationMedia.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PlayableSpecializationsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PvpTalentElement.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/SpellTooltip.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/TalentTier.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/TalentTierElement.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PlayableSpecializationApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Playable Specialization API.  Added an IWarcraftClientPlayableSpecializationApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IWarcraftClientGameDataApi interface.
> Added support for the Playable Specialization API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/AzeriteEssenceApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IAzeriteEssenceApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/AzeriteEssence/AzeriteEssence.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/AzeriteEssence/AzeriteEssenceMedia.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/AzeriteEssence/AzeriteEssenceReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/AzeriteEssence/AzeriteEssencesIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/AzeriteEssence/Power.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/AzeriteEssenceApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Azerite Essence API.  Added an IAzeriteEssenceApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IGameDataApi interface.
> Added support for the Azerite Essence API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/PowerTypeApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IAzeriteEssenceApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IPowerTypeApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PowerType/PowerType.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PowerType/PowerTypesIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/PowerTypeApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Power Type API.  Added an IPowerTypeApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IGameDataApi interface.
> Added support for the Power Type API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/RegionApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IRegionApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Region/Region.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Region/RegionsIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/RegionApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Region API.  Added an IRegionApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IGameDataApi interface.
> Added support for the Region API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterHunterPetsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterHunterPetsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Creature/CreatureDisplayMediaReference.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterHunterPets/CharacterHunterPetsSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterHunterPets/HunterPet.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterHunterPetsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Hunter Pets API.  Added an ICharacterHunterPetsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Hunter Pets API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterEquipmentApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterEquipmentApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/AzeriteEssence/AzeritEssenceMediaReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/FactionRequirement.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/ItemMediaReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/ItemReferenceWithoutName.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/ItemSpell.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/Requirements.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Item/Stat.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/SpellTooltip.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAppearance/CharacterAppearanceSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAppearance/EquippedItemAppearance.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/Armor.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/AzeriteDetails.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/CharacterEquipmentSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/EquippedItem.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/NameDescription.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/SelectedEssence.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/SelectedPower.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/Socket.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/Transmog.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterEquipmentApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Equipment API.  Added an ICharacterEquipmentApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Equipment API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterProfessionsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterProfessionsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Profession/SkillTierReferenceWithoutKey.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfessions/CharacterProfession.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfessions/CharacterProfessionsSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfessions/CharacterSkillTier.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterProfessionsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Professions API.  Added an ICharacterProfessionsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Professions API

- .config/dotnet-tools.json
- Added dotnet-format to the tools manifest, dotnet-tools.json.
- Updated the version of trx2junit from 1.3.0 to 1.3.1.
> Added dotnet-format to the tools manifest and updated trx2junit

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterEncountersApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterEncountersApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterDungeons.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterEncounter.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterEncountersSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterExpansionInstances.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterInstance.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterInstanceMode.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterInstanceProgress.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterRaids.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterEncountersApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Encounters API.  Added an ICharacterEncountersApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Encounters API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterPvpApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterPvpApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterPvp/CharacterPvpBracketStatistics.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterPvp/CharacterPvpSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterPvp/PvpMapStatistic.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterPvp/PvpMatchStatistics.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterPvpApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character PvP API.  Added an ICharacterPvpApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character PvP API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterQuestsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterQuestsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterQuests/CharacterCompletedQuests.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterQuests/CharacterQuests.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterQuestsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Quests API.  Added an ICharacterQuestsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Quests API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/ReputationsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IReputationsApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationFaction.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationFactionsIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationTier.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationTierReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationTierReferenceWithoutName.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationTiers.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Reputation/ReputationTiersIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/ReputationsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Reputations API.  Added an IReputationsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IGameDataApi interface.
> Added support for the Reputations API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterReputationsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterReputationsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterReputations/CharacterReputationsSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterReputations/Paragon.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterReputations/Reputation.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterReputations/Standing.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterReputationsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Reputations API.  Added an ICharacterReputationsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Reputations API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterStatisticsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterStatisticsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterStatistics/CharacterStatisticsSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterStatistics/CorruptionStatistics.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterStatistics/PrimaryStatistic.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterStatistics/RatingStatistic.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterStatistics/RatingStatisticWithoutValue.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterStatisticsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Statistics API.  Added an ICharacterStatisticsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Statistics API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/TitleApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/ITitleApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableClass/GenderName.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Title/Title.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Title/TitlesIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/TitleApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Title API.  Added an ITitleApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IGameDataApi interface.
> Added support for the Title API

- src/ArgentPonyWarcraftClient/Client/GameDataApi/WowTokenApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IWowTokenApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/WowToken/WowTokenIndex.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/WowTokenApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the WoW Token API.  Added an IWowTokenApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IGameDataApi interface.
> Added support for the WoW Token API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterTitlesApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterTitlesApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Title/TitleReferenceWithDisplayString.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Title/TitlesIndex.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfile/CharacterProfileSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterTitles/CharacterTitlesSummary.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterTitlesApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Titles API.  Added an ICharacterTitlesApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Titles API

- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterSpecializationsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterSpecializationsApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/PvpTalentElementForAbility.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PlayableSpecialization/SpellTooltipForAbility.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSpecializations/CharacterSpecialization.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSpecializations/CharacterSpecializationsSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSpecializations/PvpTalentSlot.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSpecializations/TalentSelection.cs
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterSpecializationsApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Specializations API.  Added an ICharacterSpecializationsApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.
> Added support for the Character Specializations API

- src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ArgentPonyWarcraftClient.Extensions.DependencyInjection.csproj
- src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
Removed the **System.ComponentModel.Annotations** dependency from **ArgentPonyWarcraftClient.csproj**.  Updated **ArgentPonyWarcraftClient.Extensions.DependencyInjection.csproj** by adding **SourceLink**, a `ContinuousIntegrationBuild` property, and adding a little detail to the `Title` attribute.  See https://github.com/clairernovotny/DeterministicBuilds for additional details on the `ContinuousIntegrationBuild` setting.
> Minor changes to csproj files

- src/ArgentPonyWarcraftClient/Client/WarcraftClient.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/AchievementProgress.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/Achievement/RecentEvent.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystonePeriod.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneSeason.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/LeadingGroup.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/MythicKeystoneLeaderboard.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicRaidLeaderboard/MythicRaidLeaderboardEntry.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/PvpSeason/PvpSeason.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/WowToken/WowTokenIndex.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterAchievements/Statistic.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEncounters/CharacterEncounter.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MythicKeystoneRun.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfile/CharacterProfileSummary.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/Guild/Guild.cs
- src/ArgentPonyWarcraftClient/Utilities/EpochConverter.cs
Replaced instances of DateTime with DateTimeOffset and updated the EpochConverter accordingly.
> Replaced DateTime with DateTimeOffset

- src/ArgentPonyWarcraftClient/Client/WarcraftClient.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneDungeon/MythicKeystoneUpgrade.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/MythicKeystoneLeaderboard/LeadingGroup.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MythicKeystoneRun.cs
- src/ArgentPonyWarcraftClient/Utilities/MillisecondTimeSpanConverter.cs
Added a MillisecondTimeSpanConverter class and converted some duration properties from long to TimeSpan.
> Converted some duration properties from long to TimeSpan

- src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
- src/ArgentPonyWarcraftClient/Client/ProfileApi/CharacterMediaApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/ICharacterMediaApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/ProfileApi/IProfileApi.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMedia/CharacterMediaSummary.cs
- tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
- tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
- tests/ArgentPonyWarcraftClient.Integration.Tests/ProfileApi/CharacterMediaApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj
- tests/ArgentPonyWarcraftClient.Tests/ProfileApi/CharacterMediaApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Character Media API.  Added an ICharacterMediaApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IProfileApi interface.  Fixes #156.
Also updated NuGet packages for unit tests:
- Microsoft.NET.Test.Sdk: 16.2.0 and 16.6.1 to 16.7.1
- xunit: 2.4.0 to 2.4.1
- xunit.runner.visualstudio: 2.4.0 and 2.4.2 to 2.4.3
- coverlet.collector: 1.0.1 to 1.3.0
> Added support for the Character Media API

- src/ArgentPonyWarcraftClient.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
- src/ArgentPonyWarcraftClient/Client/GameDataApi/ModifiedCraftingApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IGameDataApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/IModifiedCraftingApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingCategory.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingCategoryIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingCategoryReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingReagentSlotType.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingReagentSlotTypeIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/ModifiedCrafting/ModifiedCraftingReagentSlotTypeReference.cs
- tests/ArgentPonyWarcraftClient.Integration.Tests/GameDataApi/ModifiedCraftingApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/ModifiedCraftingApiTests.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.Designer.cs
- tests/ArgentPonyWarcraftClient.Tests/Properties/Resources.resx
Added support for the Modified Crafting API.  Added an IModifiedCraftingApi interface to describe the capabilities of the API.  The IWarcraftClient interface implements this interface via the IGameDataApi interface.  Resolves #160.
> Added support for the Modified Crafting API

- tests/ArgentPonyWarcraftClient.Tests/GameDataApi/CovenantApiTests.cs
Ran dotnet format, which reordered a using statement in one file.
> Ran dotnet format

- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/Enchantment.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterEquipment/EquippedItem.cs
- tests/ArgentPonyWarcraftClient.Integration.Tests/ProfileApi/GuildApiTests.cs
Created PR from this repo.
See #177 for more information
> Added Enchantments to EquippedItem

- src/ArgentPonyWarcraftClient/Models/GameDataApi/Covenant/CovenantProgress.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterProfile/CharacterProfileSummary.cs
> added covenant progress property to the CharacterProfileSummary

- .config/dotnet-tools.json
- Directory.Build.props
- src/ArgentPonyWarcraftClient/ArgentPonyWarcraftClient.csproj
- tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests/ArgentPonyWarcraftClient.Extensions.DependencyInjection.Tests.csproj
- tests/ArgentPonyWarcraftClient.Integration.Tests/ArgentPonyWarcraftClient.Integration.Tests.csproj
- tests/ArgentPonyWarcraftClient.Tests/ArgentPonyWarcraftClient.Tests.csproj
Updated NuGet packages:
* Nerdbank.GitVersioning from 3.3.37 to [3.4.220](https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.4.220)
* Microsoft.NET.Test.Sdk from 16.9.1 to [16.10.0](https://github.com/microsoft/vstest-docs/blob/master/docs/releases.md#16100)
* System.Text.Json from 5.0.1 to [5.0.2](https://www.nuget.org/packages/System.Text.Json/5.0.2)
> Updated NuGet packages

- .github/workflows/codeql-analysis.yml
- version.json
Changed references to the `master` branch to `main`.
> Changed master to main

- Directory.Build.props
- README.md
Updated content in the **README.md** to be more relevant to currently supported versions of .NET and .NET Framework.  Updated the copyright date to 2023.
> Updated README.md and copyright date

- src/ArgentPonyWarcraftClient/Client/GameDataApi/TalentApi.cs
- src/ArgentPonyWarcraftClient/Interfaces/GameDataApi/ITalentApi.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentNode.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentNodeRank.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentNodeTooltip.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentNodeType.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentTree.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentTreeIndex.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentTreeMediaReference.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentTreeNodes.cs
- src/ArgentPonyWarcraftClient/Models/GameDataApi/TalentTree/TalentTreeRestrictionLine.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CharacterMythicKeystoneProfileIndex.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/CharacterMythicKeystoneSeasonDetails.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MythicKeystoneRun.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterMythicKeystoneProfile/MythicRating.cs
Add support for new Dragonflight Talent API and update Mythic Keystone Profile models
> Add support for new Dragonflight changes

- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSpecializations/CharacterSpecialization.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSpecializations/LoadoutTalent.cs
- src/ArgentPonyWarcraftClient/Models/ProfileApi/CharacterSpecializations/SpecializationLoadout.cs
> feat: added loadout field to Character Specializations API response.

- src/ArgentPonyWarcraftClient/Client/WarcraftClient.cs
reverting back my GetOAuthHost() changes, causing issues with oauth process.
> Revert "fix: updated oauth hosts according battlenet api docs."
